apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zn3f7hgne-go 
  janus-idp.io/tekton: zn3f7hgne-go
  backstage.io/kubernetes-id: zn3f7hgne-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zn3f7hgne-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml