apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zn3f7hgne-go
  janus-idp.io/tekton: zn3f7hgne-go
  backstage.io/kubernetes-id: zn3f7hgne-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zn3f7hgne-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
