apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zn3f7hgne-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zn3f7hgne-go 
  name: zn3f7hgne-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zn3f7hgne-go 
